"""
FastAPI backend for the AI sales analytics app.

Endpoints:
    GET  /health   - liveness check (API + database connectivity)
    POST /ask      - the main pipeline: question -> SQL -> execute -> results

Run locally:
    cd backend/app
    uvicorn main:app --reload --port 8000

Then visit http://localhost:8000/docs for interactive API docs
(auto-generated by FastAPI from the type hints below).
"""

import os
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).parent.parent.parent / ".env")

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
from google.genai.errors import APIError

from query_generator import QueryGenerator, QueryGenerationError
from schema_context import get_schema_dict
from rate_limiter import RateLimiter

app = FastAPI(
    title="Sales Analytics API",
    description="Natural language to SQL analytics over the Olist e-commerce star schema.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173", "http://127.0.0.1:5173",
        "http://localhost:3000", "http://127.0.0.1:3000",
        "https://sales-analytics-webapp.vercel.app",
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

_generator: QueryGenerator | None = None
_readonly_engine = None

# 10 questions per 5 minutes per visitor. Generous enough for genuine
# exploration of the demo, tight enough that one visitor can't burn the
# whole shared Gemini quota (5 requests/minute on the free tier, per the
# GEMINI_MODEL currently in use) for everyone else.
ask_limiter = RateLimiter(max_requests=10, window_seconds=300)


def get_generator() -> QueryGenerator:
    global _generator
    if _generator is None:
        _generator = QueryGenerator()
    return _generator


def get_engine():
    global _readonly_engine
    if _readonly_engine is None:
        readonly_url = os.getenv("READONLY_DATABASE_URL")
        if not readonly_url:
            raise RuntimeError("READONLY_DATABASE_URL not set in .env")
        _readonly_engine = create_engine(readonly_url)
    return _readonly_engine


class AskRequest(BaseModel):
    question: str


class AskResponse(BaseModel):
    question: str
    sql: str
    explanation: str
    columns: list[str]
    rows: list[list]
    row_count: int
    generation_attempts: int


@app.get("/health")
def health_check():
    checks = {"api": "ok", "database": "unknown"}

    try:
        engine = get_engine()
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        checks["database"] = "ok"
    except Exception as e:
        checks["database"] = f"error: {e}"

    healthy = all(v == "ok" for v in checks.values())
    if not healthy:
        raise HTTPException(status_code=503, detail=checks)

    return checks


@app.get("/schema")
def get_schema():
    """Table/column/relationship metadata for the frontend's schema explorer."""
    return get_schema_dict()


@app.post("/ask", response_model=AskResponse)
def ask(request: AskRequest, http_request: Request):
    client_id = ask_limiter.get_client_id(http_request)
    allowed, retry_after = ask_limiter.check(client_id)
    if not allowed:
        raise HTTPException(
            status_code=429,
            detail=f"Rate limit reached. Try again in {retry_after} seconds.",
            headers={"Retry-After": str(retry_after)},
        )

    question = request.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    generator = get_generator()

    try:
        result = generator.generate_sql(question)
    except QueryGenerationError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except APIError as e:
        raise HTTPException(
            status_code=503,
            detail="The AI service is temporarily overloaded. Please try again in a moment.",
        )

    try:
        engine = get_engine()
        with engine.connect() as conn:
            cursor_result = conn.execute(text(result["sql"]))
            columns = list(cursor_result.keys())
            rows = [list(row) for row in cursor_result.fetchall()]
    except SQLAlchemyError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Query validated but failed to execute: {e}",
        )

    return AskResponse(
        question=question,
        sql=result["sql"],
        explanation=result["explanation"],
        columns=columns,
        rows=rows,
        row_count=len(rows),
        generation_attempts=result["attempts"],
    )