"""
FastAPI backend for the AI sales analytics app.

Endpoints:
    GET  /health   - liveness check (API + database connectivity)
    POST /ask      - the main pipeline: question -> SQL -> execute -> results

Run locally:
    cd backend/app
    uvicorn main:app --reload --port 8000

Then visit http://localhost:8000/docs for interactive API docs
(auto-generated by FastAPI from the type hints below).
"""

import os
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).parent.parent.parent / ".env")

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from query_generator import QueryGenerator, QueryGenerationError

app = FastAPI(
    title="Sales Analytics API",
    description="Natural language to SQL analytics over the Olist e-commerce star schema.",
    version="0.1.0",
)

# Allow the frontend dev server to call this API. Tighten this to a
# specific origin before deploying anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# --- Shared, module-level instances -----------------------------------
# Created ONCE at startup, not per-request. This matters specifically
# for QueryGenerator: it tracks rate-limit timing as instance state, so
# a new instance per request would silently defeat the rate limiting
# that keeps us under the Gemini free-tier quota.
_generator: QueryGenerator | None = None
_readonly_engine = None


def get_generator() -> QueryGenerator:
    global _generator
    if _generator is None:
        _generator = QueryGenerator()
    return _generator


def get_engine():
    global _readonly_engine
    if _readonly_engine is None:
        readonly_url = os.getenv("READONLY_DATABASE_URL")
        if not readonly_url:
            raise RuntimeError("READONLY_DATABASE_URL not set in .env")
        _readonly_engine = create_engine(readonly_url)
    return _readonly_engine


# --- Request / response schemas ----------------------------------------

class AskRequest(BaseModel):
    question: str


class AskResponse(BaseModel):
    question: str
    sql: str
    explanation: str
    columns: list[str]
    rows: list[list]
    row_count: int
    generation_attempts: int


# --- Endpoints -----------------------------------------------------------

@app.get("/health")
def health_check():
    checks = {"api": "ok", "database": "unknown"}

    try:
        engine = get_engine()
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        checks["database"] = "ok"
    except Exception as e:
        checks["database"] = f"error: {e}"

    healthy = all(v == "ok" for v in checks.values())
    if not healthy:
        raise HTTPException(status_code=503, detail=checks)

    return checks


@app.post("/ask", response_model=AskResponse)
def ask(request: AskRequest):
    question = request.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    generator = get_generator()

    try:
        result = generator.generate_sql(question)
    except QueryGenerationError as e:
        # This is a "the LLM couldn't produce valid SQL" failure, not a
        # server error -- 422 (Unprocessable Entity) fits better than 500.
        raise HTTPException(status_code=422, detail=str(e))

    try:
        engine = get_engine()
        with engine.connect() as conn:
            cursor_result = conn.execute(text(result["sql"]))
            columns = list(cursor_result.keys())
            rows = [list(row) for row in cursor_result.fetchall()]
    except SQLAlchemyError as e:
        # The SQL passed validation but failed at execution (e.g. a
        # semantic issue sqlglot's structural checks can't catch).
        raise HTTPException(
            status_code=500,
            detail=f"Query validated but failed to execute: {e}",
        )

    return AskResponse(
        question=question,
        sql=result["sql"],
        explanation=result["explanation"],
        columns=columns,
        rows=rows,
        row_count=len(rows),
        generation_attempts=result["attempts"],
    )